import { Location } from './location';

export const LOCATIONS: Location[] = [
  
  {key: "assets/images/1-SMS/1_SMS-01.png",
    name: "Smith Media Studios",
    nameKey:"SMS",
    resources: [],
    filtResources: ["Software Support", "Computers", "Printing", "Whiteboard"],
    hourNotes:"",
    hours: ["12:00PM - 12:00AM", "8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 5:00PM", "10:00AM - 5:00PM"],
    filtHours:["12:00-24:00","8:00-24:00","8:00-24:00","8:00-24:00","8:00-24:00","8:00-17:00","10:00-17:00"],
    accessNotes: "Access may be restricted by occassional course workshops. Notices of scheduled workshops will be posted outside of lab",
    access: true,
    location: "Henshaw Unit D",
    accessibility: "1st floor spaces are wheelchair accessible",
    image: "assets/images/1-SMS/picture.jpeg",
    contact:[],
    dot:"assets/images/1-SMS/1-01.png",
    dotLocation:["10vh","10vh"]
    },

    { key: "assets/images/2-Spatial Analysis Lab/2_SAL-01.png",
    name: "Spatial Analysis Lab",
    nameKey:"SAL",
    resources: ["20 Windows computers with standard Science Center software profile", "GIS, Remote Sensing, Photogrammetry applications."],
    filtResources: ["Software Support", "Computers", "Whiteboard"],
    hourNotes: "Not available during classes or workshops or meetings.  See Spatial Analysis Lab calendar for staffed hours.",
    hours: ["8:00AM-10:00PM","7:00AM - 11:00PM","7:00AM - 11:00PM","7:00AM - 11:00PM","7:00AM - 11:00PM","7:00AM - 11:00PM"
  ,"8:00AM-10:00PM",],
    filtHours:["8:00-22:00","7:00-23:00","7:00-23:00","7:00-23:00","7:00-23:00","7:00-23:00","8:00-22:00"],
    accessNotes: "Priority given to students enrolled in classes using the SAL.  Not available during class use.  Project system for instructor use only.",
    access: true,
    location: "Sabin-Reed 104",
    accessibility: "Wheelchair accessible",
    image: "assets/images/2-Spatial Analysis Lab/picture.jpeg",
    contact:[{name:"Jon Caris", email:"jcaris@smith.edu"}],
    dot:"assets/images/2-Spatial Analysis Lab/2-01.png",
    dotLocation:["10vh","10vh"]
    },

    {key: "assets/images/3-CDF/3_CDF-01.png",
    name: "The Center for Design and Fabrication",
    nameKey:"CDF",
    resources: ["Machine shop tools including Lathes, Mills and CNC router.", "Laser cutting and engraving.", "Four 3D printers.", "Wood working tools, saws, sanders, etc.", "Computer Aided Design teaching and support."],
    filtResources: ["Lasercutter", "3D printer", "Other fabrication tools", "Woodworking", "Computers", "Printing", "Whiteboard" ],
    hourNotes: "Scheduled appointments take precedence over drop in, though dropins are welcome!",
    hours: ["Closed", "8:30AM - 4:30PM","8:30AM - 4:30PM","8:30AM - 4:30PM","8:30AM - 4:30PM","8:30AM - 4:30PM","Closed"],
    filtHours:["24:00-0:00","8:30-16:30","8:30-16:30","8:30-16:30","8:30-16:30","8:30-16:30","24:00-0:00"],
    access: true,
    accessNotes: "Staff Support required",
    location: "McConnell B07/B09",
    accessibility: "Wheelchair accessible. Elevator.",
    image: "assets/images/3-CDF/picture.jpeg",
    contact:[{name:"Eric Jensen", email:"ejensen@smith.edu"},{name: "Dale Renfrow",email:"drenfrow@smith.edu"}],
    dot:"assets/images/3-CDF/3-01.png",
    dotLocation:["10vh","10vh"]
    },

    {key: "assets/images/4-DTI/4_DTI-01.png",
    name: "Design Thinking Initiative Studios",
    nameKey:"DTIS",
    resources: ["Vinyl cutter", "3D printer", "Laser cutter", "Craft supplies", "Sewing machine and hand tools!"],
    filtResources: ["Lasercutter","3D printer","Other fabrication tools", "Arts and crafts supplies",
  "Computers", "Whiteboard"],
    hours: ["1:00PM - 4:00PM", "9:00AM - 5:00PM, 6:30PM - 9:30PM","9:00AM - 5:00PM, 6:30PM - 9:30PM","9:00AM - 5:00PM, 6:30PM - 9:30PM","9:00AM - 5:00PM, 6:30PM - 9:30PM", "9:00AM - 5:00PM", "1:00PM - 4:00PM"],
    hourNotes:"Hours subject to change, check http://smithiesdesign.com/prototyping-in-capen-annex/ for updates.",
    filtHours:["13:00-16:00","9:00-17:00","9:00-17:00","9:00-17:00","9:00-17:00","9:00-17:00","13:00-16:00"],
    access: true,
    accessNotes: "Accessible 9-5 without staff support; after hours access for students with lasercutting training",
    location: "Capen Annex Room 203",
    accessibility: "Not wheelchair accessible. Please contact llilienkamp@smith.edu if you are interested in using equipment and we can work to make appropriate acomodations.",
    image: "assets/images/4-DTI/picture.jpeg",
    contact:[{name: "Laura Lilienkamp",email:"llilienkamp@smith.edu"}],
    dot:"assets/images/4-DTI/4-01.png",
    dotLocation:["10vh","10vh"]
    },

    {key: "assets/images/5-JMM/5_creative_co_op-01.png",
    name: "Creative Co-op at Jandon Center",
    nameKey:"CCJC",
    resources: ["Support but not limited to our Crafting for Community STEAM Outreach Initiative"],
    filtResources: ["Arts and craft supplies"],
    hourNotes:"Hours subject to change during breaks and over the summer.",
    hours: ["Closed", "4:00PM - 6:00PM","Closed","Closed","Closed","1:00PM - 3:00PM", "Closed"],
    filtHours:["24:00-0:00","16:00-18:00","24:00-0:00","24:00-0:00","24:00-0:00","13:00-15:00","24:00-0:00"],
    access: true,
    accessNotes: "Special activities, workshops and requests may fall outside regular hours",
    location: "Wright Hall Room 13",
    accessibility: "1st Floor is wheelchair accessible",
    image: "assets/images/5-JMM/Jandon_1.jpg",
    contact:[{name:"Deborah Day",email:"dday@smith.edu"}],
    dot:"assets/images/5-JMM/5-01.png",
    dotLocation:["10vh","10vh"]
    },

    {key: "assets/images/6-Resource Room/6_resourcerm-01.png",
    name: "The Resource Room",
    nameKey:"RR",
    resources: ["Poster-making supplies", "Photocopier", "Markerpaints", "Arts & crafts supplies"],
    filtResources: ["Arts and craft supplies","Whiteboard"],
    hourNotes:"Hours subject to change during breaks",
    hours: ["9:00AM - 11:30PM", "7:30AM - 11:30PM","7:30AM - 11:30PM","7:30AM - 11:30PM","7:30AM - 11:30PM","7:30AM - 11:30PM", "9:30AM - 11:30PM"],
    filtHours:["9:00-23:30","7:30-23:30","7:30-23:30","7:30-23:30","7:30-23:30","7:30-23:30","9:30-23:30"],
    access: true,
    accessNotes: "Available when Campus Center is open",
    location: "Campus Center Room 203",
    accessibility: "Wheelchair accessible via elevator",
    image: "assets/images/6-Resource Room/picture.jpeg",
    contact:[{name:"Sara McGuire",email:"smcguire@smith.edu"}],
    dot:"assets/images/6-Resource Room/6-01.png",
    dotLocation:["10vh","10vh"]
    },

    {key: "assets/images/7-Imaging Center/7_imagingctr-01.png",
    name: "The Imaging Center",
    nameKey:"TIC",
    resources: ["3D printer", "Large paper cutter", "Adobe Suite and 3D editing software", "iMac computers", "Large format printer.", "Contact staff for 3D scanning and poster printing support."],
    filtResources: ["3D printer", "Software support", "Computers", "Printing", "Whiteboard"],
    hourNotes:"No use during lectures",
    hours: ["Closed","8:30AM -4:30PM","8:30AM - 4:30PM","8:30AM - 4:30PM","8:30AM - 4:30PM","8:30AM - 4:30PM","Closed"],
    filtHours:["24:00-0:00","8:30-16:30","8:30-16:30","8:30-16:30","8:30-16:30","8:30-16:30","24:00-0:00"],
    access: true,
    accessNotes: "24/7 keycard access for Art History students, open to others 8:30 to 4:30 M-F",
    location: "Hillyer H324",
    accessibility: "Wheelchair accessible",
    image: "assets/images/7-Imaging Center/imaging center photo.jpg",
    contact:[{name: "Nick Baker", email:"ncbaker@smith.edu"}],
    dot:"assets/images/7-Imaging Center/7-01.png",
    dotLocation:["10vh","10vh"]
    },

    {key: "assets/images/8-Gaming Lab/8_gaminglab-01.png",
    name: "The Gaming Lab",
    nameKey:"TGL",
    resources: ["Gaming equipment includes:", "3 gaming PCs", "Arcade cabinet", "HTC Vive", "Oculus Rift", "Playstation VR", "2 PS4s", "Xbox One", "PS3", "XBox 360", "Nintendo Switch", "Game library"],
    filtResources: ["Computers"],
    hourNotes:"Occasionally reserved for class projects",
    hours: ["Closed","3:00PM - 6:00PM","3:00PM - 6:00PM","Closed","3:00PM - 8:00PM","6:00PM - 10:00PM","Closed"],
    filtHours:["24:00-0:00","15:00-18:00","15:00-18:00","24:00-0:00","15:00-20:00","18:00-22:00","24:00-0:00"],
    access: true,
    accessNotes: "Open to entire campus during posted Open Hours (check Facebook page for current semester hours: https://www.facebook.com/gaminglabatsmithcollege/). Accessible 24/7 by students enrolled in gaming-related classes (via door keycode). Also open via appointment.",
    location: "Hillyer H326",
    accessibility: "Wheelchair accessible via elevator",
    image: "assets/images/8-Gaming Lab/picture.jpeg",
    contact:[{name: "Andrew Maurer",email:"ajmaurer@smith.edu"}],
    dot:"assets/images/8-Gaming Lab/8-01.png",
    dotLocation:["10vh","10vh"]
    },

    {key: "assets/images/9-Hilyer Woodshop/9_hwoodshop-01.png",
    name: "The Hillyer Woodshop",
    nameKey:"THW",
    resources: ["Woodworking"],
    filtResources: ["Woodworking"],
    hourNotes:"When Jim is available",
    hours: ["Closed", "9:00AM - 4:00PM","9:00AM - 4:00PM","9:00AM - 4:00PM","9:00AM - 4:00PM","9:00AM - 4:00PM","Closed"],
    filtHours:["24:00-0:00","9:00-16:00","9:00-16:00","9:00-16:00","9:00-16:00","9:00-16:00","24:00-0:00"],
    access: true,
    accessNotes: "Available to drop-in when Jim Hume is in the woodshop",
    location: "Hillyer Basement",
    accessibility: "Wheelchair accessible",
    image: "assets/images/9-Hilyer Woodshop/Woodshop_1.jpg",
    contact:[{name:"James Hume", email:"jhume@smith.edu"}],
    dot:"assets/images/9-Hilyer Woodshop/9-01.png",
    dotLocation:["10vh","10vh"]
    },

  { key: "assets/images/10-Landscape Studies Studio/10_lss-01.png",
    name: "Landscape Studies Studio",
    nameKey:"LSS",
    resources: ["10 Windows machines", "Spiral binding machine", "Large format printer", "Low fidelity model building tools and supplies", "Trace paper", "Milk crates"],
    filtResources: ["Other fabrication tools", "Arts and craft supplies", "Software support", "Computers", "Printing", "Whiteboard"],
    hourNotes:"OneCard Accessible 24/7",
    hours: [],
    filtHours:["0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00"],
    access: false,
    accessNotes: "Limited to students enrolled in a LSS class - subject to change",
    location: "Burton Room 406",
    accessibility: "Wheelchair accessible via Sabin-Burton elevator",
    image: "assets/images/10-Landscape Studies Studio/picture.jpeg",
    contact:[{name:"Reid Bertone-Johnson",email:"rbertone@smith.edu"}],
    dot:"assets/images/10-Landscape Studies Studio/10-01.png",
    dotLocation:["10vh","10vh"]
  },
    
    
    {key: "assets/images/11-EGR Studio/11_egr studio-01.png",
    name: "Engineering Studio",
    nameKey:"ES",
    resources: ["Hand tools", "Electronics", "Craft & proto materials", "Floor drain"],
    filtResources: ["Arts and crafts supplies", "Computers", "Whiteboard"],
    hourNotes:"No use during lectures",
    hours: [],
    filtHours:["0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00"],
    access: false,
    accessNotes: "24/7 swipe for EGR students, others by request; staff support by request",
    location: "Burton B016, B017",
    accessibility: "Wheelchair accessible via Sabin/Burton elevator; power assist door B016",
    image: "assets/images/11-EGR Studio/picture.jpeg",
    contact:[{name:"Sue Froehlich", email:"sfroehli@smith.edu"}],
    dot:"assets/images/11-EGR Studio/11-01.png",
    dotLocation:["10vh","10vh"]
    },

    {key: "assets/images/12-Mechanics Playground/12_mechanics playground-01.png",
    name: "Mechanics Playground",
    nameKey:"MP",
    resources: ["Hand tools", "Concrete station", "Sewing machine", "Craft & proto materials", "Electronics", "Soldering", "Basic lab equipment", "Overhead lift points", "Unistrut wall; overhead water", "Air & exhaust", "Bike tools", "Ladders", "Lasercutter", "3D printer in FH002",  "Tornado machine!"],
    filtResources: ["Lasercutter", "3D printer","Other fabrication tools","Arts and craft supplies", "Software support", "Computers", "Printing", "Whiteboard"],
    hourNotes:"Scheduled lecture/lab needs take priority, but 022 workspace available during lectures in 024.",
    hours: [],
    filtHours:["0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00"],
    access: false,
    accessNotes: "24/7 swipe for EGR students, others by request; staff support weekdays",
    location: "Ford Hall LL 022, 024, 002",
    accessibility: "Accessible for humans & most projects via exterior 1.5-door @ grade level; 'forklift accessible' but no cars",
    image: "assets/images/12-Mechanics Playground/picture.jpeg",
    contact:[{name:"Sue Froehlich", email:"sfroehli@smith.edu"}],
    dot:"assets/images/12-Mechanics Playground/12-01.png",
    dotLocation:["10vh","10vh"]
    },
    
    {key: "assets/images/13-Theater Scene Shop/13_theater_scene-01.png",
    name: "Theatre Scene Shop",
    nameKey:"TSS",
    resources: ["Wood-shop and scene-shop tools", "Painting supplies", "Cloth-dying", "Hand tools", "Table saw", "Drill press", "Spray booth", "etc"],
    filtResources: ["Woodworking"],
    hourNotes:"Accesssible per request",
    hours: ["Closed", "8:00AM - 4:00PM","8:00AM - 4:00PM","8:00AM - 4:00PM","8:00AM - 4:00PM","8:00AM - 4:00PM","Closed"],
    filtHours:["24:00-0:00","8:00-16:00","8:00-16:00","8:00-16:00","8:00-16:00","8:00-16:00","24:00-0:00"],
    access: false,
    accessNotes: "Available by appointment.",
    location: "Mendenhall [behind the stage]",
    accessibility: "Wheelchair accessible",
    image: "assets/images/13-Theater Scene Shop/theater set shop photo.JPG",
    contact:[{name:"Daniel D. Rist", email:"drist@smith.edu"},{name:"Alan Schneider",email:"awschneider@smith.edu"}],
    dot:"assets/images/13-Theater Scene Shop/13-01.png",
    dotLocation:["10vh","10vh"]
    },

    {key: "assets/images/14-Costume Shop/14_costume shop-01.png",
    name: "The Costume Shop",
    nameKey:"TCS",
    resources: ["Sewing machines", "Dress forms", "Iron and steaming", "Flat patterning tools"],
    filtResources: ["Other fabrication tools","Arts and craft supplies","Computers","Printing"],
    hours: ["Closed", "9:00AM - 5:00PM","9:00AM - 5:00PM","9:00AM - 5:00PM","9:00AM - 5:00PM","9:00AM - 5:00PM", "Closed"],
    hourNotes:"Closed for lunch from 12-1",
    filtHours:["24:00-0:00","9:00-17:00","9:00-17:00","9:00-17:00","9:00-17:00","9:00-17:00","24:00-0:00"],
    accessNotes: "Limited to students enrolled in Costume Classes",
    access: false,
    location: "Mendenhall Room T12",
    accessibility: "Wheelchair accessible via elevator",
    image: "assets/images/14-Costume Shop/CostumeShop_2.jpg",
    contact:[{name:"Emily Dunn", email:"edunn2@smith.edu"}],
    dot:"assets/images/14-Costume Shop/14-01.png",
    dotLocation:["10vh","10vh"]
    },
    
    {key: "assets/images/15-Hillyer Art Studios/15_hilyer studios-01.png",
    name: "Hillyer Art Studios",
    nameKey:"HAS",
    resources: ["Discipline specific studios including:", "Darkrooms", "Digital labs", "Print studio","Sculpture studio","Typography studio"],
    filtResources: ["Other fabrication tools","Arts and craft supplies"],
    hours: [],
    hourNotes:"24/7 access for students enrolled in classes.",
    filtHours:["0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00","0:00-24:00"],
    access: false,
    accessNotes: "Open to students in art classes using studio space only.",
    location: "Hillyer Art Building",
    accessibility: "Wheelchair accessible",
    image: "assets/images/15-Hillyer Art Studios/HilyerClassroom_1.jpg",
    contact:[{name:"Fraser Stables", email:"fstables@smith.edu"}],
    dot:"assets/images/15-Hillyer Art Studios/15-01.png",
    dotLocation:["10vh","10vh"]
    }
    
];