import { Location } from './infoStructures';

export const MEDIASTUDIOS: Location[] = [
    {key: "assets/images/1-SMS/1 sms-01.jpeg",
    name: "Media Studio",
    nameKey: "",
    resources: ["16 Apple iMacs", "Full Adobe Suite, Final Cut Pro & associated software, and more","4 HD Displays connected to instructor iMac"],
    filtResources: ["Software Support", "Computers", "Printing", "Whiteboard"],
    hourNotes:"",
    hours: ["12:00PM - 12:00AM", "8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 5:00PM", "10:00AM - 5:00PM"],
    filtHours:["12:00-24:00","8:00-24:00","8:00-24:00","8:00-24:00","8:00-24:00","8:00-17:00","10:00-17:00"],
    accessNotes: "Access may be restricted by occassional course workshops. Notices of scheduled workshops will be posted outside of lab",
    access: true,
    location: "102",
    accessibility: "1st floor spaces are accessible",
    image: "assets/images/1-SMS/picture.jpeg",
    contact:[{name:"Yasmin Eisenhaue", email:"yeisenhauer@smith.edu"}],
    dot:"",
    },

    {key: "assets/images/1-SMS/1 sms-01.jpeg",
    name: "Television Studio",
    nameKey: "",
    resources: ["3 JVC High Definition Camcorders","Lighting Grid & Board","Teleprompter","Boom & Lavalier Mics",
    "Mic Stands","Black, Blue & Grey backdrops","Green Screen","Blue Screen Modular News Set","Modular Staging",
     "HTC Vive Virtual Reality HMD & Windows PC"],
    filtResources: [],
    hourNotes:"Available by appointment",
    hours: [],
    filtHours:[],
    accessNotes: "Requires appointment and brief training session. Virtual Reality sessions require two people",
    access: true,
    location: "104",
    accessibility: "1st floor spaces are accessible",
    image: "assets/images/1-SMS/picture.jpeg",
    contact:[{name:"Jeff Heath",email:"jheath@smith.edu"}],
    dot:"",
    },
    {key: "assets/images/1-SMS/1 sms-01.jpeg",
    name: "Media Duplication",
    nameKey: "",
    resources: ["2 Apple iMacs with full Adobe Suite Final Cut Pro & associated software, and more.","1 Blu-Ray Player",
    "2 VHS Players","2 DVD Players","1 Audio Cassette Deck"],
    filtResources: [],
    hourNotes:"",
    hours: ["12:00PM - 12:00AM", "8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 12:00AM", "8:00AM - 5:00PM", "10:00AM - 5:00PM"],
    filtHours:[],
    accessNotes: "Blank DVDs may be purchased at front desk",
    access: true,
    location: "105",
    accessibility: "1st floor spaces are accessible",
    image: "assets/images/1-SMS/picture.jpeg",
    contact:[{name:"Sandy Bynceski",email:"sbycenski@smith.edu"}],
    dot:"",
    },
    {key: "assets/images/1-SMS/1 sms-01.jpeg",
    name: "Audio Booth",
    nameKey: "",
    resources: ["Apple iMacs with full Adobe Suite, Final Cut Pro & associated software, and more.", "Apogee Duet Audio Interface", "Rode NT1A Condensor Mic"],
    filtResources: [],
    hourNotes:"Available by appointment",
    hours: ["12:00PM - 12:00AM", "8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 12:00AM", "8:00AM - 5:00PM", "10:00AM - 5:00PM"],
    filtHours:[],
    accessNotes: "Walk-in access or by reservation @ x2954",
    access: true,
    location: "106",
    accessibility: "1st floor spaces are accessible",
    image: "assets/images/1-SMS/picture.jpeg",
    contact:[{name:"Yasmin Eisenhaue", email:"yeisenhauer@smith.edu"}],
    dot:"",
    },
    {key: "assets/images/1-SMS/1 sms-01.jpeg",
    name: "Equipment Loan",
    nameKey: "",
    resources: ["Canon Vixia G20 Camcorders", "Canon 60D DSLRs","Zoom H4N Portable Audio Recorders","On-Camera LED Light Panels",
    "Manfrotto Tripods","Azden Wireless Lav Mics","Rode Videomic Shotgun Mics","Boom Mic","Wacom Tablets","Projectors",
    "Photo Reflectors", "Various Audio Cables", "Headphones"],
    filtResources: [],
    hourNotes: "Equipment is loaned in 3 day periods: M-W, W-F, F-M. Equipment is due by by 1:00pm on due date. Late fees applied at a rate of $5 per hour late. Loan renewal requires return of equipment in-person. Reservations can be made by phone @ x2954",
    hours: ["12:00PM - 12:00AM", "8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 12:00AM","8:00AM - 12:00AM", "8:00AM - 5:00PM", "10:00AM - 5:00PM"],
    filtHours:[],
    accessNotes: "Requires registration with Smith Media Studios",
    access: true,
    location: "Lobby",
    accessibility: "1st floor spaces are accessible",
    image: "assets/images/1-SMS/picture.jpeg",
    contact:[{name:"Sandy Bynceski",email:"sbycenski@smith.edu"}],
    dot:"",
    },
    
]